/*

Developer: Tanner A.

Date: 8/27/2026

*/

// Copyright 2026 Tanner A. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Engine/DeveloperSettings.h"
#include "CommentCommitHelperSettings.generated.h"

/**
 * Project-wide settings for Comment Commit Helper.
 *
 * These settings are available under:
 * Project Settings -> Plugins -> Comment Commit Helper
 */
UCLASS(
	Config=Editor,
	DefaultConfig,
	meta=(DisplayName="Comment Commit Helper")
)
class COMMENTCOMMITHELPER_API UCommentCommitHelperSettings : public UDeveloperSettings
{
	GENERATED_BODY()

public:
	UCommentCommitHelperSettings();

	virtual FName GetCategoryName() const override;
	virtual FName GetSectionName() const override;

	/** Include Blueprint comment-box nodes. */
	UPROPERTY(
		Config,
		EditAnywhere,
		Category="Comments",
		meta=(DisplayName="Include Comment Boxes")
	)
	bool bIncludeCommentBoxes = true;

	/** Include text entered in Blueprint node comment bubbles. */
	UPROPERTY(
		Config,
		EditAnywhere,
		Category="Comments",
		meta=(DisplayName="Include Node Comment Bubbles")
	)
	bool bIncludeNodeComments = true;

	/**
	 * If this list is not empty, only comments beginning with one of these
	 * prefixes are considered. Matching is case-insensitive.
	 *
	 * Example: adding "@commit" makes the plugin opt-in: only comments
	 * beginning with @commit are included.
	 */
	UPROPERTY(
		Config,
		EditAnywhere,
		Category="Comments|Include Filters",
		meta=(DisplayName="Required Comment Prefixes")
	)
	TArray<FString> RequiredCommentPrefixes;

	/**
	 * Remove the matched required prefix from the generated commit message.
	 * Example: "@commit Added stamina" becomes "Added stamina".
	 */
	UPROPERTY(
		Config,
		EditAnywhere,
		Category="Comments|Include Filters",
		meta=(DisplayName="Strip Required Prefix From Output")
	)
	bool bStripRequiredPrefixFromOutput = true;

	/** Ignore comments beginning with any of these values. Case-insensitive. */
	UPROPERTY(
		Config,
		EditAnywhere,
		Category="Comments|Ignore Filters",
		meta=(DisplayName="Ignored Comment Prefixes")
	)
	TArray<FString> IgnoredCommentPrefixes;

	/** Ignore comments containing any of these values. Case-insensitive. */
	UPROPERTY(
		Config,
		EditAnywhere,
		Category="Comments|Ignore Filters",
		meta=(DisplayName="Ignored Comment Text Contains")
	)
	TArray<FString> IgnoredCommentContains;

	/** Ignore comments that exactly match one of these values. Case-insensitive. */
	UPROPERTY(
		Config,
		EditAnywhere,
		Category="Comments|Ignore Filters",
		meta=(DisplayName="Ignored Exact Comments")
	)
	TArray<FString> IgnoredExactComments;

	/**
	 * Always ignore Unreal's autogenerated disabled-node message:
	 * "This node is disabled and will not be called..."
	 */
	UPROPERTY(
		Config,
		EditAnywhere,
		Category="Comments|Ignore Filters",
		meta=(DisplayName="Ignore Unreal Disabled Node Messages")
	)
	bool bIgnoreUnrealDisabledNodeMessages = true;

	/**
	 * If this list is not empty, only assets under one of these package paths
	 * are scanned. Example: /Game/Blueprints/
	 */
	UPROPERTY(
		Config,
		EditAnywhere,
		Category="Assets|Include Filters",
		meta=(DisplayName="Included Asset Paths")
	)
	TArray<FString> IncludedAssetPaths;

	/** Ignore assets under these package paths. Example: /Game/ThirdParty/ */
	UPROPERTY(
		Config,
		EditAnywhere,
		Category="Assets|Ignore Filters",
		meta=(DisplayName="Ignored Asset Paths")
	)
	TArray<FString> IgnoredAssetPaths;

	/** Ignore assets whose short name begins with one of these values. */
	UPROPERTY(
		Config,
		EditAnywhere,
		Category="Assets|Ignore Filters",
		meta=(DisplayName="Ignored Asset Name Prefixes")
	)
	TArray<FString> IgnoredAssetNamePrefixes;

	/**
	 * Strip a leading @tag from generated commit text.
	 *
	 * Examples:
	 * @commit Added stamina -> Added stamina
	 * @fix Fixed collision -> Fixed collision
	 * @ui Updated HUD -> Updated HUD
	 *
	 * Only applies when the @tag is at the very start of the comment.
	 */
	UPROPERTY(
		Config,
		EditAnywhere,
		Category="Comments|Output",
		meta=(DisplayName="Strip Leading @ Tag From Output")
	)
	bool bStripLeadingAtTagFromOutput = true;

	/**
	 * Prefix used by the cleanup button to identify temporary commit comments.
	 * Matching is case-insensitive.
	 *
	 * Example: @commit Added stamina regeneration
	 */
	UPROPERTY(
		Config,
		EditAnywhere,
		Category="Comments|Cleanup",
		meta=(DisplayName="Commit Cleanup Prefix")
	)
	FString CommitCleanupPrefix = TEXT("@commit");

	/** Include newly added source-control assets that do not have a prior revision. */
	UPROPERTY(
		Config,
		EditAnywhere,
		Category="Source Control",
		meta=(DisplayName="Include Newly Added Assets")
	)
	bool bIncludeAddedAssets = true;

	/** Include modified source-controlled assets. */
	UPROPERTY(
		Config,
		EditAnywhere,
		Category="Source Control",
		meta=(DisplayName="Include Modified Assets")
	)
	bool bIncludeModifiedAssets = true;
};
